// Generated by CoffeeScript 1.9.2
(function() {
  var $, b, bi, d, di, f, fi, generateImages, k, l, li, pllalgs, r, ri, show, u, ui, v;

  $ = jQuery;

  b = "./images/b.png";

  bi = "./images/bi.png";

  d = "./images/d.png";

  di = "./images/di.png";

  f = "./images/f.png";

  fi = "./images/fi.png";

  l = "./images/l.png";

  li = "./images/li.png";

  r = "./images/r.png";

  ri = "./images/ri.png";

  u = "./images/u.png";

  ui = "./images/ui.png";

  pllalgs = {
    "T-Perm": "R U R' U' R' F R2 U' R' U' R U R' F'",
    "J(a)-Perm": "R' U L' U2 R U' R' U2 R L U'",
    "J(b)-Perm": "R U R' F' R U R' U' R' F R2 U' R' U'",
    "R(a)-Perm": "R U R' F' R U2 R' U2 R' F R U R U2 R' U'",
    "R(b)-Perm": "R' U2 R U2 R' F R U R' U' R' F' R2 U'",
    "F-Perm": "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R",
    "Y-Perm": "F R U' R' U' R U R' F' R U R' U' R' F R F'"
  };

  show = function(n) {
    return $("#images").append("<img src=" + n + " />");
  };

  generateImages = function() {
    var i, len, move, notation, results;
    $("#images").empty();
    notation = $("#notation").val().split(" ");
    results = [];
    for (i = 0, len = notation.length; i < len; i++) {
      move = notation[i];
      switch (move) {
        case "B":
          results.push(show(b));
          break;
        case "B'":
          results.push(show(bi));
          break;
        case "D":
          results.push(show(d));
          break;
        case "D'":
          results.push(show(di));
          break;
        case "F":
          results.push(show(f));
          break;
        case "F'":
          results.push(show(fi));
          break;
        case "L":
          results.push(show(l));
          break;
        case "L'":
          results.push(show(li));
          break;
        case "R":
          results.push(show(r));
          break;
        case "R'":
          results.push(show(ri));
          break;
        case "U":
          results.push(show(u));
          break;
        case "U'":
          results.push(show(ui));
          break;
        case "B2":
          show(b);
          results.push(show(b));
          break;
        case "D2":
          show(d);
          results.push(show(d));
          break;
        case "F2":
          show(f);
          results.push(show(f));
          break;
        case "L2":
          show(l);
          results.push(show(l));
          break;
        case "R2":
          show(r);
          results.push(show(r));
          break;
        case "U2":
          show(u);
          results.push(show(u));
          break;
        default:
          results.push(void 0);
      }
    }
    return results;
  };

  $("#generateImages").on("click", function(event) {
    return generateImages();
  });

  $("#pll-algs").on("change", function(event) {
    var selected;
    selected = $("#pll-algs").find(":selected").text();
    $("#notation").val(pllalgs[selected]);
    return generateImages();
  });

  for (k in pllalgs) {
    v = pllalgs[k];
    $("#pll-algs").append("<option>" + k + "</option>");
  }

  $("#notation").val(pllalgs["T-Perm"]);

  generateImages();

}).call(this);
